server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

razorpay-secret:
  key-id: rzp_test_aAQrXOzUsjeNME
  key-secret: ERvXuSqHZ8g7ReaGWV3AYkjL

logging:
  level: INFO
  loggers:
    com.credair: DEBUG
  appenders:
    - type: console