server:
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083

logging:
  level: INFO
  loggers:
    com.credair: DEBUG
  appenders:
    - type: console